---
- name: Install git maven and java on devserver
  hosts: devserver
  tasks:
    - name: Install required s/w's
      apt:
        name: "{{item.a}}"
        state: present
        update_cache: "{{item.b}}"
      with_items:
        - {a: git,b: yes}
        - {a: openjdk-11-jdk,b: no}
        - {a: maven,b: no}
- name: Install git maven and tomcat on qaserver
  hosts: qaserver
  tasks:
    - name: Install required s/w's
      apt:
        name: "{{item.a}}"
        state: present
        update_cache: "{{item.b}}"
      with_items:
        - {a: git,b: yes}
        - {a: openjdk-11-jdk,b: no}
        - {a: tomcat9,b: no}
        - {a: tomcat9-admin,b: no}
- name: Install tomcat on prodservers
  hosts: prodserver
  tasks:
    - name: Install required s/w's
      apt:
        name: "{{item.a}}"
        state: present
        update_cache: "{{item.b}}"
      with_items:
        - {a: tomcat9,b: yes}
        - {a: tomcat9-admin,b: no}
- name: Continuous dwonload and Continuous Build
  hosts: devserver
  tasks:
    - name: Download dev code from github
      git:
        repo: https://github.com/intelliqittrainings/maven.git
        dest: dev-git
    - name: Create an artifact from the above code
      shell: cd dev-git;mvn package
    - name: Fetch the artifact from devserver o controller
      fetch: 
       src: dev-git/webapp/target/webapp.war
       dest: /tmp
- name: Continuous Deployment and Continuous Testing
  hosts: qaserver
  tasks:
    - name: Deploy artifact into tomcat on qaserver
      copy:
        src: /tmp/172.31.54.78/dev-git/webapp/target/webapp.war
        dest: /var/lib/tomcat9/webapps/testapp.war
    - name: Download selenium scripts
      git:
        repo: https://github.com/intelliqittrainings/FunctionalTesting.git
        dest: test-git
    - name: Execute selenium scripts
      shell: java -jar test-git/testing.jar
- name: Continuous Delivery
  hosts: prodserver
  tasks:
    - name: Deploy artifact into tomcay on prodserver
      copy:
        src: /tmp/172.31.54.78/dev-git/webapp/target/webapp.war
        dest: /var/lib/tomcat9/webapps/prodapp.war












