---
- name: Download docker images
  hosts: all
  serial: 1
  tasks:
    - name: Pull docker images
      docker_image:
        name: "{{item}}"
        source: pull
      with_items:
        - nginx
        - tomee
        - ghost
        - httpd
