---
- name: Create users and copy files inot users home dir
  hosts: all
  tasks:
    - name: Create users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: ball,b: apple,c: /tmp/ball}
        - {a: bat,b: apple,c: /tmp/bat}
    - name: Copy files into users home dir
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /tmp/ball}
        - {a: /etc/group,b: /tmp/bat}

