---
- name: Implementing docker compose using ansible
  hosts: all
  tasks:
    - name: Create a mysql container
      docker_container:
        name: mydb
        image: mysql:5
        env:
          MYSQL_ROOT_PASSWORD: apple

    - name: Create a wordpress container
      docker_container:
        name: mywordpress
        image: wordpress
        ports:
          - 8989:80
        links:
          - mydb:mysql

