---
- name: Working on docker containers
  hosts: all
  tasks:
    - name: Create a tomee container
      docker_container:
        name: webserver
        image: tomee
    - name: Stop the tomee container
      docker_container:
        name: webserver
        state: stopped
    - name: Delete the tomee container
      docker_container:
        name: webserver
        state: absent

