---
- name: Capture OS info of all managed nodes
  hosts: all
  tasks:
    - name: Captyure OS name
      debug:
        msg: "{{ansible_distribution}}"
    - name: Capture major version no
      debug:
        msg: "{{ansible_distribution_major_version}}"
    - name: Capture OS version
      debug:
        msg: "{{ansible_distribution_version}}"
